### ISSUE TITLE
Список чего?

### ISSUE THREAD

**Issue by coursar** [bobojohn/telegram#2]
https://github.com/bobojohn/telegram/blob/7d2ffaafef3143a4c51724122ebbc2e13cb61eed/src/componenrs/List/List.js#L3

**Comment by bobojohn** [comment]
список контактов в телеграм которые пользователь последний раз разговаривал с ними
извините учитель у меня русский не очень хорошо  я не знаю мои слова вам понятно или как

**Comment by coursar** [comment]
Надо не объяснения писать, а исправлять

**Comment by coursar** [comment]
И это не список, это у вас один контакт отображается

**Comment by bobojohn** [comment]
хорошо буду исправить
